package server

import (
	"encoding/json"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

func (s *Server) handleConfig(w http.ResponseWriter, req *http.Request) {
	s.cors(w)

	if req.Method == http.MethodOptions {
		w.WriteHeader(http.StatusNoContent)
		return
	}

	if !s.validateAuth(req) {
		w.WriteHeader(http.StatusUnauthorized)
		json.NewEncoder(w).Encode(map[string]string{"error": "Unauthorized"})
		return
	}

	if req.Method == http.MethodGet {
		s.handleConfigGet(w)
		return
	}

	if req.Method == http.MethodPost {
		s.handleConfigPost(w, req)
		return
	}

	http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
}

func (s *Server) handleConfigGet(w http.ResponseWriter) {
	env := loadEnv()
	for _, value := range os.Environ() {
		parts := strings.SplitN(value, "=", 2)
		if len(parts) == 2 && env[parts[0]] == "" {
			env[parts[0]] = parts[1]
		}
	}

	type ModelEntry struct {
		Name          string  `json:"name"`
		Provider      string  `json:"provider"`
		Model         string  `json:"model"`
		BaseURL       string  `json:"base_url"`
		EnvKey        string  `json:"env_key"`
		ModelEnvKey   *string `json:"model_env_key"`
		BaseURLEnvKey *string `json:"base_url_env_key"`
		Available     bool    `json:"available"`
	}

	textModels := []ModelEntry{
		{Name: "Claude", Provider: "anthropic", Model: env["ANTHROPIC_MODEL"], EnvKey: "ANTHROPIC_API_KEY", Available: env["ANTHROPIC_API_KEY"] != "" && env["ANTHROPIC_API_KEY"] != "sk-ant-..."},
		{Name: "OpenAI", Provider: "openai", Model: env["OPENAI_MODEL"], EnvKey: "OPENAI_API_KEY", Available: env["OPENAI_API_KEY"] != "" && env["OPENAI_API_KEY"] != "sk-..."},
		{Name: "DeepSeek", Provider: "deepseek", Model: env["DEEPSEEK_MODEL"], EnvKey: "DEEPSEEK_API_KEY", Available: env["DEEPSEEK_API_KEY"] != ""},
	}

	ttsModels := []ModelEntry{
		{Name: "Mimo TTS", Provider: "mimo", Model: env["MIMO_TTS_MODEL"], EnvKey: "MIMO_API_KEY", Available: env["MIMO_API_KEY"] != ""},
		{Name: "OpenAI TTS", Provider: "openai", Model: env["OPENAI_TTS_MODEL"], EnvKey: "OPENAI_API_KEY", Available: env["OPENAI_API_KEY"] != ""},
	}

	envVars := make(map[string]string)
	for _, model := range textModels {
		envVars[model.EnvKey] = env[model.EnvKey]
	}
	for _, model := range ttsModels {
		envVars[model.EnvKey] = env[model.EnvKey]
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(map[string]interface{}{
		"text":       textModels,
		"tts":        ttsModels,
		"multimodal": []ModelEntry{},
		"envVars":    envVars,
	})
}

func (s *Server) handleConfigPost(w http.ResponseWriter, req *http.Request) {
	var body struct {
		EnvVars map[string]string `json:"envVars"`
	}

	if !decodeJSON(w, req, &body) {
		return
	}
	if body.EnvVars == nil {
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "envVars object is required"})
		return
	}

	existing := loadEnv()
	for key, value := range body.EnvVars {
		existing[key] = value
	}

	lines := []string{
		"# OfferPilot model configuration (generated by the settings UI)",
		"# Manual edits are preserved",
		"",
	}
	groups := []struct {
		Label string
		Keys  []string
	}{
		{Label: "Text models", Keys: []string{"ANTHROPIC_API_KEY", "ANTHROPIC_BASE_URL", "ANTHROPIC_MODEL", "OPENAI_API_KEY", "OPENAI_BASE_URL", "OPENAI_MODEL", "DEEPSEEK_API_KEY", "DEEPSEEK_BASE_URL", "DEEPSEEK_MODEL"}},
		{Label: "Text to speech", Keys: []string{"MIMO_API_KEY", "MIMO_BASE_URL", "MIMO_TTS_MODEL", "OPENAI_TTS_MODEL"}},
		{Label: "Speech recognition", Keys: []string{"MIMO_ASR_MODEL", "OPENAI_ASR_MODEL"}},
	}

	written := make(map[string]bool)
	for _, group := range groups {
		lines = append(lines, "# --- "+group.Label+" ---")
		for _, key := range group.Keys {
			if existing[key] != "" {
				lines = append(lines, key+"="+existing[key])
				written[key] = true
			}
		}
		lines = append(lines, "")
	}
	for key, value := range existing {
		if !written[key] && value != "" {
			lines = append(lines, key+"="+value)
		}
	}

	envPath := envFilePath()
	if err := os.WriteFile(envPath, []byte(strings.Join(lines, "\n")+"\n"), 0644); err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(map[string]bool{"ok": true})
}

func loadEnv() map[string]string {
	env := make(map[string]string)
	data, err := os.ReadFile(envFilePath())
	if err != nil {
		return env
	}

	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		equals := strings.Index(line, "=")
		if equals == -1 {
			continue
		}
		key := strings.TrimSpace(line[:equals])
		value := strings.TrimSpace(line[equals+1:])
		env[key] = value
	}
	return env
}

func envFilePath() string {
	path := filepath.Join(os.Getenv("PROJECT_ROOT"), ".env")
	if path == ".env" {
		return filepath.Join("..", ".env")
	}
	return path
}
